// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDBProject.Models;

namespace MyDBProject.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20220504104712_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyDBProject.Models.Bank", b =>
                {
                    b.Property<int>("Bank_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bank_IFSC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bank_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Bank_id");

                    b.ToTable("Banks");
                });
#pragma warning restore 612, 618
        }
    }
}
